"""Generate the Windows VERSIONINFO resource embedded into ChineseStudy.exe.

Windows reads this resource for the file's Properties → Details tab, for the
SmartScreen prompt and for the UAC dialog. A binary with no version resource
shows blank fields, which both users and reputation systems treat as a red flag.
Populating it does not replace a code-signing certificate, but it is a
prerequisite for the executable to present itself as a real product.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from backend import APP_NAME, APP_SLUG, COMPANY_NAME, COPYRIGHT, __version__  # noqa: E402

OUTPUT_FILE = ROOT_DIR / "build" / "version_info.txt"

TEMPLATE = """# UTF-8
#
# Generated by scripts/version_info.py -- do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, 0),
    prodvers=({major}, {minor}, {patch}, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName', u'{company}'),
        StringStruct(u'FileDescription', u'{description}'),
        StringStruct(u'FileVersion', u'{version}'),
        StringStruct(u'InternalName', u'{slug}'),
        StringStruct(u'LegalCopyright', u'{copyright}'),
        StringStruct(u'OriginalFilename', u'{slug}.exe'),
        StringStruct(u'ProductName', u'{product}'),
        StringStruct(u'ProductVersion', u'{version}'),
        StringStruct(u'Comments', u'{comments}')])
      ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""

DESCRIPTION = "Ung dung hoc tieng Trung HSK 1-9"
COMMENTS = "Offline HSK study app. Data stays on this computer."


def _version_parts() -> tuple[int, int, int]:
    numbers = [int(part) for part in __version__.split(".")[:3] if part.isdigit()]
    while len(numbers) < 3:
        numbers.append(0)
    return numbers[0], numbers[1], numbers[2]


def render() -> str:
    major, minor, patch = _version_parts()
    return TEMPLATE.format(
        major=major,
        minor=minor,
        patch=patch,
        version=__version__,
        company=COMPANY_NAME,
        product=APP_NAME,
        slug=APP_SLUG,
        copyright=COPYRIGHT,
        description=DESCRIPTION,
        comments=COMMENTS,
    )


def write(path: Path | None = None) -> Path:
    target = path or OUTPUT_FILE
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render(), encoding="utf-8")
    return target


if __name__ == "__main__":
    print(f"Wrote {write()}")
