"""HSKK mock exam: assemble a paper from the curated bank and score it.

The HSKK is a *spoken* test, so nothing here can be graded automatically. The
exam runner plays the prompt, records the learner and asks them to rate their
own answer — the same self-assessment loop the flashcard drill already uses.
This service owns the paper layout (parts, item counts, points, timings) so the
frontend never has to hardcode the format, and it owns the score arithmetic so
a client cannot invent its own points.

The item bank is a static JSON file shipped with the app rather than something
generated by an external model: the packaged .exe has to work offline and the
repo must not need an API key (see AGENTS.md). Variety comes from sampling a
fresh subset of each pool per attempt, so two sittings are never the same paper.
"""

from __future__ import annotations

import json
import random
from functools import lru_cache
from typing import Any

from backend.database import get_connection, utc_now
from backend.services.errors import InvalidOperationError, ResourceNotFoundError
from scripts.seed_data import FULL_DATA_DIR


BANK_FILE = "hskk_bank.json"

# How much of an item's points a self-rating is worth. Deliberately generous at
# the bottom: the learner did speak, they just were not happy with it.
RATING_WEIGHTS: dict[str, float] = {
    "good": 1.0,
    "ok": 0.6,
    "bad": 0.2,
    "skipped": 0.0,
}

RATING_LABELS: dict[str, str] = {
    "good": "Trôi chảy",
    "ok": "Tạm được",
    "bad": "Còn vấp",
    "skipped": "Bỏ qua",
}


@lru_cache(maxsize=1)
def _load_bank() -> dict[str, Any]:
    path = FULL_DATA_DIR / BANK_FILE
    if not path.is_file():
        raise InvalidOperationError("Không tìm thấy ngân hàng đề HSKK.")
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def _get_level(exam_level: str) -> dict[str, Any]:
    level = _load_bank()["levels"].get(exam_level)
    if not level:
        raise ResourceNotFoundError("Không có cấp độ HSKK này.")
    return level


def _part_config(exam_level: str, part: int) -> dict[str, Any]:
    for config in _get_level(exam_level)["parts"]:
        if config["part"] == part:
            return config
    raise ResourceNotFoundError("Đề HSKK không có phần này.")


def list_levels() -> dict[str, Any]:
    """Format summary for the intro screen — no items, so it is cheap to poll."""
    items = []
    for code, level in _load_bank()["levels"].items():
        parts = [
            {
                "part": part["part"],
                "kind": part["kind"],
                "title": part["title"],
                "instruction_zh": part["instruction_zh"],
                "instruction_vi": part["instruction_vi"],
                "count": part["count"],
                "points_per_item": part["points_per_item"],
                "total_points": round(part["count"] * part["points_per_item"], 1),
                "answer_seconds": part["answer_seconds"],
            }
            for part in level["parts"]
        ]
        items.append(
            {
                "code": code,
                "label": level["label"],
                "hsk_range": level["hsk_range"],
                "blurb": level["blurb"],
                "prep_seconds": level["prep_seconds"],
                "pass_score": level["pass_score"],
                "total_items": sum(part["count"] for part in level["parts"]),
                "total_points": round(sum(part["total_points"] for part in parts), 1),
                "parts": parts,
            }
        )
    return {"items": items}


def _build_paper(level: dict[str, Any]) -> list[dict[str, Any]]:
    parts = []
    for config in level["parts"]:
        pool = level["pools"][str(config["part"])]
        count = min(config["count"], len(pool))
        chosen = random.sample(pool, count)
        parts.append(
            {
                "part": config["part"],
                "kind": config["kind"],
                "title": config["title"],
                "instruction_zh": config["instruction_zh"],
                "instruction_vi": config["instruction_vi"],
                "points_per_item": config["points_per_item"],
                "answer_seconds": config["answer_seconds"],
                "min_sentences": config.get("min_sentences"),
                "items": [
                    {
                        "question_index": index,
                        "question_id": item["id"],
                        "hanzi": item["hanzi"],
                        "pinyin": item["pinyin"],
                        "vi": item["vi"],
                        "hints": item.get("hints", []),
                        # Part 1 and 2 are heard, never read: the runner must not
                        # show the text before the learner has answered.
                        "audio_text": item["hanzi"] if config["kind"] in {"repeat", "answer"} else None,
                    }
                    for index, item in enumerate(chosen)
                ],
            }
        )
    return parts


def create_session(exam_level: str) -> dict[str, Any]:
    level = _get_level(exam_level)
    parts = _build_paper(level)
    total_items = sum(len(part["items"]) for part in parts)
    max_score = round(
        sum(len(part["items"]) * part["points_per_item"] for part in parts), 1
    )

    with get_connection() as connection:
        cursor = connection.execute(
            """
            INSERT INTO hskk_sessions (exam_level, started_at, total_items, max_score)
            VALUES (?, ?, ?, ?)
            """,
            (exam_level, utc_now(), total_items, max_score),
        )
        session_id = cursor.lastrowid

    return {
        "session_id": session_id,
        "exam_level": exam_level,
        "label": level["label"],
        "prep_seconds": level["prep_seconds"],
        "pass_score": level["pass_score"],
        "total_items": total_items,
        "max_score": max_score,
        "parts": parts,
    }


def _get_open_session(connection: Any, session_id: int) -> Any:
    session = connection.execute(
        "SELECT * FROM hskk_sessions WHERE id = ?", (session_id,)
    ).fetchone()
    if not session:
        raise ResourceNotFoundError("Không tìm thấy bài thi thử HSKK.")
    if session["ended_at"]:
        raise InvalidOperationError("Bài thi thử này đã nộp.")
    return session


def record_answer(
    session_id: int,
    part: int,
    question_index: int,
    question_id: str,
    self_rating: str,
    spoken_seconds: int,
) -> dict[str, Any]:
    with get_connection() as connection:
        session = _get_open_session(connection, session_id)
        config = _part_config(session["exam_level"], part)
        max_score = float(config["points_per_item"])
        score = round(max_score * RATING_WEIGHTS[self_rating], 2)
        connection.execute(
            """
            INSERT INTO hskk_answers (
                session_id, part, question_index, question_id,
                self_rating, score, max_score, spoken_seconds, created_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT (session_id, part, question_index) DO UPDATE SET
                question_id = excluded.question_id,
                self_rating = excluded.self_rating,
                score = excluded.score,
                max_score = excluded.max_score,
                spoken_seconds = excluded.spoken_seconds,
                created_at = excluded.created_at
            """,
            (
                session_id,
                part,
                question_index,
                question_id,
                self_rating,
                score,
                max_score,
                spoken_seconds,
                utc_now(),
            ),
        )
    return {
        "session_id": session_id,
        "part": part,
        "question_index": question_index,
        "self_rating": self_rating,
        "score": score,
        "max_score": max_score,
    }


def _band(percent: float) -> str:
    if percent >= 85:
        return "Rất tốt — sẵn sàng thi thật"
    if percent >= 70:
        return "Khá — cần gọt lại phát âm và độ trôi chảy"
    if percent >= 60:
        return "Vừa đủ đỗ — nên luyện thêm phần nói dài"
    return "Chưa đạt — tập trung vào phần nhắc lại trước"


def complete_session(session_id: int) -> dict[str, Any]:
    with get_connection() as connection:
        session = _get_open_session(connection, session_id)
        rows = connection.execute(
            """
            SELECT part,
                   COUNT(*) AS answered,
                   COALESCE(SUM(score), 0) AS score,
                   COALESCE(SUM(max_score), 0) AS max_score,
                   COALESCE(SUM(spoken_seconds), 0) AS spoken_seconds
            FROM hskk_answers
            WHERE session_id = ?
            GROUP BY part
            ORDER BY part
            """,
            (session_id,),
        ).fetchall()

        answered = sum(row["answered"] for row in rows)
        score = round(sum(row["score"] for row in rows), 1)
        max_score = float(session["max_score"]) or 100.0
        connection.execute(
            """
            UPDATE hskk_sessions
            SET ended_at = ?, answered_items = ?, score = ?
            WHERE id = ?
            """,
            (utc_now(), answered, score, session_id),
        )

        parts = [
            {
                "part": row["part"],
                "title": _part_config(session["exam_level"], row["part"])["title"],
                "answered": row["answered"],
                "score": round(row["score"], 1),
                "max_score": round(row["max_score"], 1),
                "spoken_seconds": row["spoken_seconds"],
            }
            for row in rows
        ]

    percent = round(score / max_score * 100, 1) if max_score else 0.0
    pass_score = _get_level(session["exam_level"])["pass_score"]
    return {
        "session_id": session_id,
        "exam_level": session["exam_level"],
        "score": score,
        "max_score": round(max_score, 1),
        "percent": percent,
        "passed": score >= pass_score,
        "pass_score": pass_score,
        "band": _band(percent),
        "total_items": session["total_items"],
        "answered_items": answered,
        "parts": parts,
    }


def get_stats() -> dict[str, Any]:
    with get_connection() as connection:
        rows = connection.execute(
            """
            SELECT exam_level, score, max_score, started_at, ended_at
            FROM hskk_sessions
            WHERE ended_at IS NOT NULL
            ORDER BY started_at DESC
            """
        ).fetchall()
        ratings = connection.execute(
            """
            SELECT self_rating, COUNT(*) AS total
            FROM hskk_answers
            GROUP BY self_rating
            """
        ).fetchall()

    scores = [row["score"] / (row["max_score"] or 100) * 100 for row in rows]
    return {
        "sessions": len(rows),
        "best_percent": round(max(scores), 1) if scores else 0,
        "average_percent": round(sum(scores) / len(scores), 1) if scores else 0,
        "last_percent": round(scores[0], 1) if scores else 0,
        "recent": [
            {
                "exam_level": row["exam_level"],
                "score": round(row["score"], 1),
                "max_score": round(row["max_score"], 1),
                "percent": round(row["score"] / (row["max_score"] or 100) * 100, 1),
                "ended_at": row["ended_at"],
            }
            for row in rows[:10]
        ],
        "ratings": [
            {
                "self_rating": row["self_rating"],
                "label": RATING_LABELS.get(row["self_rating"], row["self_rating"]),
                "total": row["total"],
            }
            for row in ratings
        ],
    }
